#!/bin/bash

### This script is called after the user change environment variables in application setting page.

CONFIG_FILE="${TRIM_PKGETC}/server.env"

mkdir -p "${TRIM_PKGETC}"
cat > "${CONFIG_FILE}" <<EOF
remote_url="${remote_url}"
EOF

exit 0
