#!/bin/bash

### This script is called before the user change environment variables in application setting page.

CONFIG_FILE="${TRIM_PKGETC}/server.env"

mkdir -p "${TRIM_PKGETC}"

if [ ! -f "${CONFIG_FILE}" ]; then
    cat > "${CONFIG_FILE}" <<EOF
remote_url="https://auth.88frp.com/config?secret={{secret}}"
EOF
fi

exit 0
